- name: Auth_Client Test
  hosts: localhost
  #connection: local
  tasks:
  - name: Auth0 Client Get
    auth0_client:
      mode: 'get'
      name: 'Test1809211036'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      output_file: 'output/client.json'
  - name: Auth0 Client GetAllClients
    auth0_client:
      mode: 'get_all'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
  #- name: Auth0 Client Assert
  #  auth0_client:
  #    mode: 'assert'
  #    name: 'Test1810010620'
  #    domain: 'allianz-uk.eu.auth0.com'
  #    clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
  #    clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
  #    client_file: 'client.json'
  - name: Auth0 Tenant Get
    auth0_tenant:
      mode: 'get'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      output_file: 'output/tenant.json'
  - name: Auth0 Email Get
    auth0_email:
      mode: 'get'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      output_file: 'output/email.json'
  # - name: Auth0 Email Get Fail - No file specified
  #   auth0_email:
  #     mode: 'get'
  #     domain: 'allianz-uk.eu.auth0.com'
  #     clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
  #     clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
  - name: Auth0 Email Update
    auth0_email:
      mode: 'assert'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      input_file: 'input/email.json'
  # - name: Auth0 Email Update Fail - No file specified
  #   auth0_email:
  #     mode: 'update'
  #     domain: 'allianz-uk.eu.auth0.com'
  #     clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
  #     clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
  - name: Auth0 Verify Email Template Get
    auth0_email_template:
      mode: 'get'
      name: 'verify_email'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      output_file: 'output/email_template_verify_email.json'
  - name: Auth0 Pwd Reset Email Template Update
    auth0_email_template:
      mode: 'assert'
      name: 'reset_email'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      input_file: 'input/email_template_post_pwd.json'
      content_file: 'input/reset_email.html'
      result_url: "https://wibble.com/"
  - name: Auth0 Pwd Reset Email Template Get
    auth0_email_template:
      mode: 'get'
      name: 'reset_email'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      output_file: 'output/email_template_reset_email.json'
  - name: Auth0 Connection Get
    auth0_connection:
      mode: 'get_all'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      output_file: 'output/connection.json'
  - name: Auth0 Resource Server Get
    auth0_resource_server:
      mode: 'get_all'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      output_file: 'output/resource_server.json'
  - name: Auth0 Rules Get
    auth0_resource_server:
      mode: 'get_all'
      domain: 'allianz-uk.eu.auth0.com'
      clientid: 'enFdkGnm0ZFbBn33aPN7V23cEYICxUGD'
      clientsecret: 'yWmJDk8jE55FGklpLU8Y1t1kHb-BFHarHZxY7nbVK24EcVxuyjuccYndxmI9TbGG'
      output_file: 'output/rules.json'
